#ifndef OBJECTSTORE_ERRCODE_H
#define OBJECTSTORE_ERRCODE_H

enum Status {

    EXECUTE_OK,
    SUBMIT_OK,
    UNSUPPORTED_OPERATION,

    OSTORE_OBJECT_EXIST = 0x11,
    OSTORE_OBJECT_NOT_EXIST,
    OSTORE_NO_SPACE,
    OSTORE_NO_NODE,
    
    OSTORE_WRITE_OUT_MAX_SIZE,
    OSTORE_READ_EOF,

};

#endif